In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
d = pd.read_csv(r"C:\Users\EKANKSH\Downloads\archive (7)\Features data set.csv")
print(d.head)

<bound method NDFrame.head of       Store        Date  Temperature  Fuel_Price  MarkDown1  MarkDown2  \
0         1  05/02/2010        42.31       2.572        NaN        NaN
1         1  12/02/2010        38.51       2.548        NaN        NaN
2         1  19/02/2010        39.93       2.514        NaN        NaN
3         1  26/02/2010        46.63       2.561        NaN        NaN
4         1  05/03/2010        46.50       2.625        NaN        NaN
...     ...         ...          ...         ...        ...        ...
8185     45  28/06/2013        76.05       3.639    4842.29     975.03
8186     45  05/07/2013        77.50       3.614    9090.48    2268.58
8187     45  12/07/2013        79.37       3.614    3789.94    1827.31
8188     45  19/07/2013        82.84       3.737    2961.49    1047.07
8189     45  26/07/2013        76.06       3.804     212.02     851.73

      MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  IsHoliday
0           NaN        NaN        NaN  211.096358         8.106      False
1           NaN        NaN        NaN  211.242170         8.106       True
2           NaN        NaN        NaN  211.289143         8.106      False
3           NaN        NaN        NaN  211.319643         8.106      False
4           NaN        NaN        NaN  211.350143         8.106      False
...         ...        ...        ...         ...           ...        ...
8185       3.00    2449.97    3169.69         NaN           NaN      False
8186     582.74    5797.47    1514.93         NaN           NaN      False
8187      85.72     744.84    2150.36         NaN           NaN      False
8188     204.19     363.00    1059.46         NaN           NaN      False
8189       2.06      10.88    1864.57         NaN           NaN      False

[8190 rows x 12 columns]>

In [3]:
print(d.isnull().sum())

Store              0
Date               0
Temperature        0
Fuel_Price         0
MarkDown1       4158
MarkDown2       5269
MarkDown3       4577
MarkDown4       4726
MarkDown5       4140
CPI              585
Unemployment     585
IsHoliday          0
dtype: int64

In [4]:
d.shape

(8190, 12)

In [5]:
marksd = ["MarkDown1","MarkDown2","MarkDown3","MarkDown4","MarkDown5"]
d[marksd] = d[marksd].fillna(0)

In [6]:
print(d.isnull().sum())

Store             0
Date              0
Temperature       0
Fuel_Price        0
MarkDown1         0
MarkDown2         0
MarkDown3         0
MarkDown4         0
MarkDown5         0
CPI             585
Unemployment    585
IsHoliday         0
dtype: int64

In [7]:
d["CPI"] = d["CPI"].ffill()
d["Unemployment"] = d["Unemployment"].ffill()

In [8]:
d["Date"] = pd.to_datetime(d["Date"])

ValueError: time data "19/02/2010" doesn't match format "%m/%d/%Y", at position 2. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [9]:
d.describe()

,Store,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
count,8190.000000,8190.000000,8190.000000,8190.000000,8190.000000,8190.000000,8190.000000,8190.000000,8190.000000,8190.000000
mean,23.000000,59.356198,3.405992,3462.090725,1206.981664,776.464219,1392.763115,2043.403725,172.855800,7.747708
std,12.987966,18.678607,0.431337,7388.916286,5495.556015,7539.953758,4707.111488,9431.223215,39.898285,1.878347
min,1.000000,-7.290000,2.472000,-2781.450000,-265.760000,-179.260000,0.000000,-185.170000,126.064000,3.684000
25%,12.000000,45.902500,3.041000,0.000000,0.000000,0.000000,0.000000,0.000000,132.653774,6.565000
50%,23.000000,60.710000,3.513000,0.000000,0.000000,0.000000,0.000000,0.000000,182.855869,7.742000
75%,34.000000,73.880000,3.743000,4639.585000,98.590000,24.220000,774.692500,2680.295000,214.367504,8.549000
max,45.000000,101.950000,4.468000,103184.980000,104519.540000,149483.310000,67474.850000,771448.100000,228.976456,14.313000

In [10]:
d.dtypes

Store             int64
Date             object
Temperature     float64
Fuel_Price      float64
MarkDown1       float64
MarkDown2       float64
MarkDown3       float64
MarkDown4       float64
MarkDown5       float64
CPI             float64
Unemployment    float64
IsHoliday          bool
dtype: object

In [ ]:
d['Date'] = pd.to_datetime(d['Date'], dayfirst=True)
d['Year'] = d['Date'].dt.year
d['Month'] = d['Date'].dt.month

In [ ]:
dsales = pd.read_csv("sales data-set.csv")
dstores = pd.read_csv("stores data-set.csv")

In [24]:
dsales.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

In [13]:
dstores.isnull().sum()
dsales['Weekly_Sales'].isnull().sum()

NameError: name 'dstores' is not defined

In [ ]:
print(dstores.head())
print(d.head())
print(dsales.head())

In [25]:
df = pd.merge(dstores,dsales,on = "Store",how = "left")

In [26]:
df = pd.merge(df,d,on=["Store","Date","IsHoliday"],how = "left")

In [27]:
df["Date"]= pd.to_datetime(df["Date"],dayfirst = True)

In [28]:
df = pd.merge(df,d,on=["Store","Date","IsHoliday"],how = "left")

ValueError: You are trying to merge on datetime64[ns] and object columns for key 'Date'. If you wish to proceed you should use pd.concat

In [29]:
df.shape

(421570, 16)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Type          421570 non-null  object
 2   Size          421570 non-null  int64
 3   Dept          421570 non-null  int64
 4   Date          421570 non-null  datetime64[ns]
 5   Weekly_Sales  421570 non-null  float64
 6   IsHoliday     421570 non-null  bool
 7   Temperature   421570 non-null  float64
 8   Fuel_Price    421570 non-null  float64
 9   MarkDown1     421570 non-null  float64
 10  MarkDown2     421570 non-null  float64
 11  MarkDown3     421570 non-null  float64
 12  MarkDown4     421570 non-null  float64
 13  MarkDown5     421570 non-null  float64
 14  CPI           421570 non-null  float64
 15  Unemployment  421570 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(10), int64(3), object(1)
memory usage: 48.6+ MB

In [31]:
df.head()

,Store,Type,Size,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
0,1,A,151315,1,2010-02-05,24924.50,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106
1,1,A,151315,1,2010-02-12,46039.49,True,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106
2,1,A,151315,1,2010-02-19,41595.55,False,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106
3,1,A,151315,1,2010-02-26,19403.54,False,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106
4,1,A,151315,1,2010-03-05,21827.90,False,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106

In [32]:
print(df.isnull().sum())

Store           0
Type            0
Size            0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
dtype: int64